id: 61d590ef18b045a49596b5f72f3a2b57
initial_creation_type: ocr
source_metadata:
  volumes:
    e34bb4735820415a8cf5070d47d71fa6:
      base_file: v095.txt
      image_group_id: I1PD95941
      title: ''
      total_pages: 1144
      volume_number: 96
